[workspace]
members = ["crates/cli", "crates/common", "crates/project", "crates/templater"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

license = "MIT"
authors = ["Zeke <ezequiel_io@pm.me>"]
homepage = "https://github.com/zeke-io/crafty"
repository = "https://github.com/zeke-io/crafty"

[workspace.dependencies]
anyhow = "1.0.81"
clap = { version = "4.3.4", features = ["derive"] }
cli = { path = "crates/cli" }
common = { path = "crates/common" }
log = "0.4"
project = { path = "crates/project" }
serde = { version = "1.0.197", features = ["derive"] }
templater = { path = "crates/templater" }
tokio = { version = "1.38.0", features = ["full"] }
url = "2.4.0"
